config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks do
    resources :todos, only: :create
  end
  get 'tasks/:id/ranking', to: 'tasks#ranking', as: 'tasks_ranking'
  
  resources :todos, only: :index
  get 'todos/sign_in/profile', to: 'todos#profile', as: 'todos_profile'
  
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :todos, dependent: :destroy
  has_many :users, through: :todos



  def completed?(user_id)
    todo = Todo.find_by(user: user_id, task: id)
    todo.done? if todo
  end

  def ranking_members
    todos.where('done_at IS NOT NULL').sort_by(&:done_at).first(5) if todos.any?
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task

  #Reference so it works with validation of two columns at the same time: https://stackoverflow.com/questions/34424154/rails-validate-uniqueness-of-two-columns-together
  validates :task_id, uniqueness: { scope: :user_id}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy
  has_many :tasks, through: :todos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def total_done
    todos.where(done: true).count
  end

  def last_done(task_id)
    todo = Todo.find_by(user: id, task: task_id)
    todo ? "Última vez realizada: #{todo.done_at}" : "Nunca realizada :c"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar_photo])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:ranking, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def ranking
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'La tarea fue creada con éxito!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :photo)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def create
    @task = Task.find(params[:task_id])
    @todo = Todo.find_by(task: @task.id, user: current_user)
    unless @todo
      @todo = Todo.new(task: @task, user: current_user, done: true, done_at: Time.now)
      if @todo.save!
        redirect_to tasks_path, notice: 'Se ha modificado el estado de tu todo :)'
      else
        redirect_to tasks_path, alert: 'No se ha podido crear el todo :('
      end
    else
      if @todo.done?
        @todo.done = false
      else
        @todo.done = true
        @todo.done_at = Time.now
      end
      @todo.save!
      redirect_to tasks_path, notice: 'Se ha modificado el estado de tu todo :)'
    end
  end
  
  def profile
    @todos = current_user.todos
  end

  private

  def todo_params
    params.require(:todo).permit(:task_id, :done, :done_at)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaDL4Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <% if notice.present? %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">2Do v2.0</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_task_path %>">Nueva Tarea</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <span class="btn btn-info">Total realizadas: 
            <span class="badge badge-light">
            <%= current_user.total_done %>
            </span>
          </span>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= user_signed_in? ? current_user.email : 'Cuenta' %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> 
          <% if user_signed_in? %>
            <a class="dropdown-item" href="<%= todos_profile_path %>">Perfil</a>
            <a class="dropdown-item" href="<%= destroy_user_session_path%>" data-method="delete">Cerrar Sesión</a>  
          <% else %>
            <a class="dropdown-item" href="<%= new_user_session_path %>">Iniciar Sesión</a>
            <a class="dropdown-item" href="<%= new_user_registration_path %>">Registrarse</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre de la Tarea" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Ingrese aquí el nombre de la nueva tarea"%>
  </div>

  <div class="field">
    <%= form.label :photo, "Link de la imagen" %>
    <%= form.text_field :photo, class:"form-control mb-3", placeholder:"Ingrese aquí la url de su imagen" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar Tarea", class:"btn btn-primary mr-2"%>
    <%= link_to 'Volver', tasks_path %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="jumbotron">
  <h1 class="text-center font-weight-bold" style="font-size: 2.5em">TAREAS DIECIOCHERAS</h1>
</div>
<div class="container-fluid">
  <% @tasks.each do |task| %>
    <div class="col-md-4 col-lg-3 col-sm-12 float-left">
      <div class="card mb-2 mt-2">
        <%= image_tag task.photo, class:'card-img-top' %>
        <div class="card-body">
          <h5 class="card-title text-center"><%= task.name %></h5>
          <% if user_signed_in? %>
            <h6 class="card-text text-center"><%= current_user.last_done(task.id) %></h5>
          <% end %>
        </div>
        <div class="btn-group align-self-center mb-2">
          <% if user_signed_in? %>  
            <% if task.completed?(current_user.id) %>
              <%= link_to "Deshacer", task_todos_path(task), method: :post, class: "btn btn-danger" %>
              <% else %>
              <%= link_to "Completar", task_todos_path(task), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
          <%= link_to "Ranking", tasks_ranking_path(task), method: :get, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
    <div class="w-100" style="margin-top: 3rem"> </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-md-4 ml-2 mt-3">
    <h1>Nueva Tarea</h1>

    <%= render 'form', task: @task %>

  </div>
</div>

app/views/tasks/ranking.html.erb
<p id="notice"><%= notice %></p>
<div class="row mr-0">
  <div class="col-md-4 ml-3">
      <h2 class="text-center">
        <span>Tarea:</span>
        <strong><%= @task.name %></strong>
      </h2>

    <div class="card mb-3">
      <%= image_tag @task.photo, class: "card-img-top" %>
      <%= link_to 'Atrás', tasks_path, class: "text-center btn-dark rounded-bottom p-2" %>
    </div>
  </div>
  <div class="col-md-7 m-3">
    <h2 class="text-center font-weight-bold">Ranking de Usuarios</h2>
      <table class="table mt-4">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" style="width: 12rem;">Foto</th>
            <th scope="col">Email</th>
            <th scope="col" style="width: 15rem;">Realizada a la fecha de:</th>
          </tr>
        </thead>
        <tbody>
        <% @task.ranking_members.each_with_index do |todo, n| %>
          <tr>
            <th scope="row"><%= (n + 1) %></th>
            <td><%= image_tag todo.user.avatar_photo, class:"card-img w-50" %> </td>
            <td><%= todo.user.email %></td>
            <td><%= time_tag todo.done_at %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/todos/profile.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1 class="text-center font-weight-bold" style="font-size: 2.5em">TAREAS DIECIOCHERAS REALIZADAS</h1>
  <h2 class="text-center font-italic">Por: <%= current_user.email%></h2>
</div>
<div class="container-fluid">
  <% @todos.each do |todo| %>
    <% if todo.task.completed?(current_user.id)%>
      <div class="col-md-4 col-lg-3 col-sm-12 float-left">
        <div class="card mx-auto mb-2">
          <%= image_tag todo.task.photo, class:'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title text-center"><%= todo.task.name %></h5>
            <h6 class="card-text text-center"><%= current_user.last_done(todo.task.id) %></h5>
            <div class="btn-group d-flex justify-content-center">
              <%= link_to "Deshacer", task_todos_path(todo.task), method: :post, class: "btn btn-danger" %>
              <%= link_to "Ranking", tasks_ranking_path(todo.task), method: :get, class: "btn btn-warning" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <div class="w-100" style="margin-top: 3rem"> </div>
  <% end %>
</div>